🐛 Fix makefile for latest .NET versions when passing an $EXE (#2578)
Prevent OB from running `dotnet publish src/Lynx.Cli/Lynx.Cli.csproj -o .`, since that's apparently no longer acceptable in latest .NET 10 versions.
Add instead a `FinalDestination` parameter with the expected final location of the publish files, in order to be able to manually move them

Context:

```bash
make 'EXE=lynx-9DB032C3'
```

invokes:
```bash
dotnet publish src/Lynx.Cli/Lynx.Cli.csproj --runtime win-x64 --self-contained /p:Optimized=true /p:ExecutableName=lynx-9DB032C3 -o ./
```

`dotnet publish src/Lynx.Cli/Lynx.Cli.csproj -o .` doesn't work for .NET SDK 10.0.201 or 10.0.301, while it did for .NET 10.0.101 and 10.0.109 🙄.

```BASH
$ dotnet publish src/Lynx.Cli/Lynx.Cli.csproj -o .
CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point
```

After this change, the following command is usedm no longer problematic:
```bash
dotnet publish src/Lynx.Cli/Lynx.Cli.csproj --runtime win-x64 --self-contained /p:Optimized=true /p:ExecutableName=lynx-9DB032C3 -o artifacts/Lynx/ /p:FinalDestination=../../ --tl:off
```